### ISSUE TITLE
Syntax error when running demo

### ISSUE THREAD

**Issue by labrat789** [songweizhi/MarkerMAG#6]
Hi there,

I recently installed MarkerMAG in our department grid using mamba, and when running the command to test on the demo dataset, this error was thrown:

MarkerMAG_env) jones@my-mgrid2-2:/proj/mykopat-ncommeg/MarkerMAG_demo_data$ MarkerMAG link -p Demo -r1 demo_R1.fasta -r2 demo_R2.fasta -marker demo_16S.fasta -mag demo_MAGs -x fa -t 16
Traceback (most recent call last):
  File "/nethomes/jones/mambaforge/envs/MarkerMAG_env/bin/MarkerMAG", line 64, in <module>
    from MarkerMAG import link_16s
  File "/nfs4/my-mgrid-s8/nethomes/jones/mambaforge/envs/MarkerMAG_env/lib/python2.7/site-packages/MarkerMAG/link_16s.py", line 4676
    arg_for_cn = {**config_dict, **args}
                   ^
SyntaxError: invalid syntax

Not sure if this is something I can fix myself, do you have any suggestions?

many thanks,
chris

**Comment by sternp** [comment]
Same issue, looks to by Python3 syntax but Python2.7 is being used. Try adjusting /nfs4/my-mgrid-s8/nethomes/jones/mambaforge/envs/MarkerMAG_env/lib/python2.7/site-packages/MarkerMAG/link_16s.py near line 4676 like so:
```
    if skip_calculate_copy_num is False:
        from MarkerMAG import get_cp_num

#        arg_for_cn = {**config_dict, **args}
        arg_for_cn = config_dict.copy()
        arg_for_cn.update(args)
```
